#define Button_Emp 0
#define Button_AjouterClient 1
#define Button_ModifierClient 2
#define Button_AjouterVoiture 3
#define Button_ModifierVoiture 4
#define Button_SupprimerVoiture 5
#define Button_Evaluer 6
#define Button_Statistique 7
#define Button_Louer 8
#define Button_StockerClient 9
#define Button_ModifierClientB 10
#define Button_ModifierVoitureB 11
#define Button_AjouterVoitureB 12
#define Button_SupprimerVoitureB 13
#define Button_VerifierClient 14
#define Button_chercherModele 15
#define Button_Calculer 16
#define Button_sortie 17
#define Button_effacer 18
#define Button_Statistique 19
#define Button_EvaluerB 20
#define Button_AjouterEmp 21
#define Button_AjouterEmpB 22
#define Button_afficherClient 23
#define Button_afficherClientB 24
#define Button_reserver 25
#define Disable_resize WS_OVERLAPPED | WS_MINIMIZEBOX | WS_SYSMENU
#define Max_Voiture 100
#define Max_Modeles_De_Marque 20
#define Remise 0.9f